/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domain.Korisnik;
import javax.swing.JOptionPane;
import transfer.Response;
import userController.UserInterfaceController;

/**
 *
 * @author x
 */
public class DodavanjeIIzmenaKorisnikaForma extends javax.swing.JDialog {

    FormaZaRadSaKorisnicima gf;
    Korisnik korisnikZaIzmenu;
    /**
     * Creates new form DodavanjeKorisnikaForma
     */
    public DodavanjeIIzmenaKorisnikaForma(java.awt.Frame parent, boolean modal,Korisnik korisnikZaIzmenu) {
        super(parent, modal);
        this.gf = (FormaZaRadSaKorisnicima)parent;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.korisnikZaIzmenu=korisnikZaIzmenu;
        jButtonIzmena.setVisible(false);
        this.setTitle("Dodavanje korisnika");
        if(!(this.korisnikZaIzmenu==null)){
            this.setTitle("Izmena korisnika");
            jButtonDodaj.setVisible(false);
            jButtonIzmena.setVisible(true);
            jTextFieldIme.setText(this.korisnikZaIzmenu.getIme());
            jTextFieldPrezime.setText(this.korisnikZaIzmenu.getPrezime());
            jTextFieldEmail.setText(this.korisnikZaIzmenu.getEmail());
            jTextFieldBrojTelefona.setText(this.korisnikZaIzmenu.getBrojTelefona());
            jLabelNaslov.setText("IZMENA KORISNIKA");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDodaj = new javax.swing.JButton();
        jLabelNaslov = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonIzmena = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBrojTelefona = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonDodaj.setText("Dodaj korisnika");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jLabelNaslov.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNaslov.setText("DODAVANJE KORISNIKA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Ime:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Prezime:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email:");

        jButtonIzmena.setText("Izmena");
        jButtonIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmenaActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Broj telefona:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonOdustani)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIzmena, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldEmail)
                        .addComponent(jTextFieldPrezime)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldIme)
                        .addComponent(jLabelNaslov, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldBrojTelefona)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelNaslov)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIzmena, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonOdustani)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        String ime=jTextFieldIme.getText();
        String prezime=jTextFieldPrezime.getText();
        String email=jTextFieldEmail.getText();
        String brojTelefona=jTextFieldBrojTelefona.getText();
        if(ime.isEmpty() || prezime.isEmpty() || email.isEmpty() || brojTelefona.isEmpty()){
            JOptionPane.showMessageDialog(this, "Neuspesno dodavanje korisnika. Sva polja moraju da budu popunjena","Upozorenje",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Neuspesno dodavanje korisnika. Email mora sadržati '@' simbol.", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Korisnik k=new Korisnik(-1, ime, prezime, email, brojTelefona, 0,gf.getUlogovaniAdmin());
        Response response=UserInterfaceController.getInstance().dodajKorisnika(k);
        if(response.isSuccessful()){
            JOptionPane.showMessageDialog(this, response.getMessage(),"Uspeh",JOptionPane.INFORMATION_MESSAGE);
            gf.popuniListuKorisnika();
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, response.getMessage(),"Greska",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmenaActionPerformed
        String ime=jTextFieldIme.getText();
        String prezime=jTextFieldPrezime.getText();
        String email=jTextFieldEmail.getText();
        String brojTelefona=jTextFieldBrojTelefona.getText();
        if(ime.isEmpty() || prezime.isEmpty() || email.isEmpty() || brojTelefona.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Neuspesna izmena korisnika. Sva polja moraju da budu popunjena","Upozorenje",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Neuspesna izmena korisnika. Email mora sadržati '@' simbol.", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        korisnikZaIzmenu.setIme(ime);
        korisnikZaIzmenu.setPrezime(prezime);
        korisnikZaIzmenu.setEmail(email);
        korisnikZaIzmenu.setBrojTelefona(brojTelefona);
        Response response=UserInterfaceController.getInstance().izmenaKorisnika(korisnikZaIzmenu);
        if(response.isSuccessful()){
            JOptionPane.showMessageDialog(this, response.getMessage(),"Uspeh",JOptionPane.INFORMATION_MESSAGE);
            gf.popuniListuKorisnika();
            this.dispose();
            return;
        }
        else{
            JOptionPane.showMessageDialog(this, response.getMessage(),"Greska",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_jButtonIzmenaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonIzmena;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNaslov;
    private javax.swing.JTextField jTextFieldBrojTelefona;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables
}
